# Generated by Django 6.0.7 on 2026-09-19 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(max_length=4000, validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='new', max_length=12)),
                ('source_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('manage_submission', 'Can manage contact submissions')],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_status_idx')],
            },
        ),
    ]
