# Generated by Django 6.0.7 on 2026-09-19 09:05

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('about', 'About'), ('skills', 'Skills'), ('services', 'Services'), ('projects', 'Projects'), ('experience', 'Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('contact', 'Contact')], max_length=24, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'section'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Portfolio', max_length=120)),
                ('site_url', models.URLField(blank=True, help_text='Canonical production URL, without a trailing slash.')),
                ('default_meta_title', models.CharField(blank=True, max_length=60)),
                ('default_meta_description', models.CharField(blank=True, max_length=160, validators=[django.core.validators.MaxLengthValidator(160)])),
                ('og_image', models.ImageField(blank=True, upload_to=apps.core.validators.safe_image_path, validators=[apps.core.validators.validate_safe_image])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_cta_label', models.CharField(default='View selected work', max_length=40)),
                ('secondary_cta_label', models.CharField(default='Get in touch', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
