# Generated by Django 6.0.7 on 2026-09-19 09:05

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('professional_title', models.CharField(max_length=160)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_statement', models.CharField(max_length=220)),
                ('hero_supporting_text', models.TextField(blank=True, max_length=600)),
                ('about_heading', models.CharField(blank=True, max_length=120)),
                ('about_body', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to=apps.core.validators.safe_image_path, validators=[apps.core.validators.validate_safe_image])),
                ('resume', models.FileField(blank=True, upload_to=apps.core.validators.safe_resume_path, validators=[apps.core.validators.validate_safe_pdf])),
            ],
            options={
                'permissions': [('manage_profile', 'Can manage the public profile')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'project categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Databases'), ('api', 'APIs'), ('automation', 'Automation'), ('devops', 'DevOps'), ('tool', 'Tools')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(max_length=160)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-issued_date', 'sort_order', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('issued_date__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('issued_date')), _connector='OR'), name='certification_expiry_after_issued')],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=160)),
                ('qualification', models.CharField(max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-end_date', '-start_date', 'sort_order'),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='education_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('summary', models.CharField(max_length=360)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Use short, truthful paragraphs or a concise list.')),
                ('role', models.CharField(blank=True, max_length=160)),
                ('challenges', models.TextField(blank=True)),
                ('results', models.TextField(blank=True, help_text='Only include substantiated outcomes.')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2027)])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portfolio.projectcategory')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology')),
            ],
            options={
                'ordering': ('-is_featured', 'sort_order', '-year', 'title'),
                'permissions': [('publish_project', 'Can publish projects')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Databases'), ('api', 'APIs'), ('automation', 'Automation'), ('devops', 'DevOps'), ('tool', 'Tools')], max_length=24)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('technologies', models.ManyToManyField(blank=True, related_name='skills', to='portfolio.technology')),
            ],
            options={
                'ordering': ('category', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=140)),
                ('position', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.technology')),
            ],
            options={
                'ordering': ('-is_current', '-start_date', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.core.validators.safe_image_path, validators=[apps.core.validators.validate_safe_image])),
                ('alt_text', models.CharField(help_text='Describe the image for visitors who cannot see it.', max_length=160)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('project', 'sort_order'), name='unique_project_image_order')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_featured', 'sort_order'], name='project_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_end_after_start'),
        ),
    ]
